name: dev
on:
  push:
    paths:
      - 'environments/dev.tfvars'


jobs:
  call:
    uses: ./.github/workflows/terraform-multi.yml
    with:
      environment: dev
      tfvars_file: environments/dev.tfvars
      rgname: ritkargs
      saname: ritkasas
      scname: ritkascs
      key: dev.tfstate
      runInit: true
      runFmt: false
      runValidate: true
      runPlan: true
      runApply: false
      runDestroy: false
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
