name: uat
on:
  push:
    paths:
      - 'environments/uat.tfvars'

permissions:
  contents: read
  id-token: write

jobs:
  call:
    uses: ./.github/workflows/terraform-multi.yml
    with:
      environment: uat
      tfvars_file: environments/uat.tfvars
      rgname: ritkargs
      saname: ritkasas
      scname: ritkascs
      key: uat.tfstate
      runInit: true
      runFmt: false
      runValidate: true
      runPlan: true
      runApply: false
      runDestroy: false
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
